using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RapidRepo.SourceGenerators;

internal static class SourceEmitter
{
    internal static string EmitInterface(
        string? namespaceName,
        string interfaceName,
        IReadOnlyList<PropertyModel> properties)
    {
        var usings = CollectUsings(properties);
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated by RapidRepo.SourceGenerators — do not edit />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        foreach (var u in usings)
            sb.AppendLine($"using {u};");

        if (usings.Count > 0) sb.AppendLine();

        if (namespaceName is not null)
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"public interface {interfaceName}");
        sb.AppendLine("{");
        foreach (var prop in properties)
            sb.AppendLine($"    {prop.TypeDisplay} {prop.Name} {{ get; }}");
        sb.AppendLine("}");

        return sb.ToString();
    }

    internal static string EmitPartialClass(
        string? namespaceName,
        string className,
        IReadOnlyList<PropertyModel> properties)
    {
        var usings = CollectUsings(properties);
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated by RapidRepo.SourceGenerators — do not edit />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        foreach (var u in usings)
            sb.AppendLine($"using {u};");

        if (usings.Count > 0) sb.AppendLine();

        if (namespaceName is not null)
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"public partial class {className}");
        sb.AppendLine("{");
        foreach (var prop in properties)
            sb.AppendLine($"    public {prop.TypeDisplay} {prop.Name} => {prop.Implementation};");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static IReadOnlyList<string> CollectUsings(IReadOnlyList<PropertyModel> properties)
    {
        return properties
            .SelectMany(p => p.Namespaces)
            .Distinct()
            .OrderBy(u => u)
            .ToList();
    }
}
