name: Release

on:
  workflow_run:
    workflows: ['Build']
    types: [completed]
    branches:
      - master
      - beta
      - pre-release

jobs:  
  semantic_release:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        issues: write
        pull-requests: write
        id-token: write
    steps:
      - name: Echo head branch name
        run: |
          'branch:'
          echo ${{ github.event.workflow_run.head_branch }}

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
            ref: ${{ github.event.workflow_run.head_branch }}        
            
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install @semantic-release/git @semantic-release/github semantic-release-replace-plugin -D

      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_HEAD: ${{ github.sha }}
