name: Build

on:
  push:
    branches:
      - master
      - beta
      - pre-release
  pull_request:
    branches:
      - master
      - beta
      - pre-release

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  ci:
    name: Build & Test
    uses: tibor-horvath/ci-toolkit/.github/workflows/dotnet-build-test.yml@v1
    with:
      dotnet-version: "10.0.x"
      runsettings: "coverlet.runsettings"
    secrets: inherit
    permissions:
      checks: write
      contents: read

  secrets:
    name: Secret scan
    uses: tibor-horvath/ci-toolkit/.github/workflows/secret-scan.yml@v1
    permissions:
      contents: read

  coverage-comment:
    name: Coverage PR Comment
    needs: ci
    if: github.event_name == 'pull_request'
    uses: tibor-horvath/ci-toolkit/.github/workflows/dotnet-coverage-comment.yml@d9c2eac3bfc76a720ed60c343d7432430a3a8c0b # v1.15.0
    with:
      dotnet-version: "10.0.x"
      thresholds: "60 80"
    permissions:
      contents: read
      pull-requests: write
