name: Release

on:
  push:
    branches:
      - master
      - beta
      - pre-release

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please-stable:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'master'
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  release-please-beta:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'beta'
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          prerelease: true
          prerelease-type: beta

  release-please-rc:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'pre-release'
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          prerelease: true
          prerelease-type: rc
