name: Publish NuGet Package

on:
  workflow_run:
    workflows: ['Release']
    types: [completed]
    branches:
      - master
      - beta
      - pre-release

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet pack --configuration Release -p:PackageVersion=${{ github.ref_name }}
    - name: Pack
      run: dotnet pack --configuration Release --no-build --output ./artifacts

    - name: Push to NuGet
      run: dotnet nuget push **/bin/Release/RapidRepo*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
